### ISSUE TITLE
Uncaught (in promise): Error: No provider for ConnectionBackend!

### ISSUE THREAD

**Issue by deniskkk** [angular-starter-kit/generator-ngx-app#60]
trying to use generated HttpService but getting error
Uncaught (in promise): Error: No provider for ConnectionBackend!

**Comment by sinedied** [comment]
Could you provide a bit more context? OS + version, nodejs/npm versions, the complete error log and the code your are trying to make working?

**Comment by deniskkk** [comment]
resolved.
I was trying to import HttpService and tried to use its methods, when its actually just overriding the default Http service.
